image: alpine/edge
packages: 
  - gcc
  - cmake
secrets:
  - 78ae6d85-5fc6-4127-a6ac-18edc14f0fcc
tasks:
  - setup: |
      ssh-keyscan github.com >> ~/.ssh/known_hosts
      git clone git@github.com:artemisbot/ModelLoader.git
      cd ModelLoader
      mkdir build
      cd build
      cmake ..
  - build: |
      cd ModelLoader
      cd build
      make ModelLoaderTest
      ./ModelLoaderTest
